### ISSUE TITLE
CS_004 - 추천 상품 노출 기능 개발

### ISSUE THREAD

**Issue by JungDongSeob** [beyond-sw-camp/be02-fin-CuStard-CRM#14]
/product/recommend 경로를 통해 POST 방식으로 최근 구매 목록 및 유사도를 통한 추천 알고리즘을 통해 추천 상품 노출 기능 개발

**Comment by Hyeon28** [comment]
추천 알고리즘 스터디(개념 학습 후 구현)

**Comment by Hyeon28** [comment]
아이템 기반 협업 필터링을 사용해 자바 코드로 구현 중
테스트 데이터 추가 작업
